version: 0.5.0.{build}

configuration: Release

before_test:
  - netsh.exe advfirewall firewall add rule name='MBrace daemon' dir=in action=allow program=.\bin\mbraced.exe enable=yes
  - netsh.exe advfirewall firewall add rule name='MBrace worker' dir=in action=allow program=.\bin\mbrace.worker.exe enable=yes
#  - Add-AppveyorMessage -Message "Created firewall rules"

test:
  assemblies:
    - MBrace.Runtime.Tests.dll
	- MBrace.Store.Tests.dll
  categories:
    - FileSystemStore
    - CompilerTests
    - LocalTests
    - ClusterTests
